// Generated by https://quicktype.io

class Register {
  String email;
  String fullName;
  String id;
  List<String> roles;
  ///String password;

  Register({
    required this.email,
    required this.fullName,
    required this.id,
    required this.roles,
    ///required this.password,
  });
}
